#
box      = 'ubuntu/trusty32'
hostname = 'ldap'
domain   = 'example.com'
ip       = '10.0.0.2'
ram      = '512'
#

Vagrant.configure("2") do |config|
    
# configure RAM on virtualbox VVM
    config.vm.provider "virtualbox" do |vb|
          vb.customize [
              'modifyvm', :id,
              '--memory', ram
          ]
      end

# update hosts file on host and guest
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

# configure and start server
    config.vm.box = box
    config.vm.host_name = hostname + '.' + domain
    config.vm.network 'private_network', ip: ip

# provision server with Ansible
    config.vm.provision 'ansible' do |ansible|
        ansible.playbook = './site.yml'
        ansible.inventory_path = './inventory'
        ansible.sudo = true
        ansible.limit = 'all'
        ansible.verbose = 'vvvv'
    end
end